In [115]:
import json,os
from cadlib.sketch import Profile
from cadlib.extrude import Extrude,CADSequence
import numpy as np
from OCC.Core.gp import gp_Pnt
import h5py
from glob import glob
import open3d as o3d
from utils.file_utils import get_files

In [146]:
f1=get_files("output")
print(len(f1))

8327


In [137]:
f2=get_files("/data/3d_cluster/CC3D-OP-SEQ/cc3d_v3.0_recs_extrude")
print(len(f2))

8488


In [138]:
(8488-8327)/8488

0.018967954759660698

In [111]:
np.array([1,2]).reshape(2,1)*np.array([1,2,3])+np.array([1,0,-1])

array([[2, 2, 2],
       [3, 4, 5]])

In [101]:
def point_transformation(points,transformation_matrix):
    """Linear Transformation of points"""
    assert len(points.shape)==2 and transformation_matrix.shape[-1]==4 and transformation_matrix.shape[-2]==4,"Wrong input format"
    N=points.shape[0]
    A=points.shape[1]
    if points.shape[1]==2:
        for i in range(2):
            points=add_axis(points,value=i)
    else:
        points=add_axis(points,1)
    points=points.reshape(-1,4,1)
    transformation_matrix=np.broadcast_to(transformation_matrix,(N,4,4))
    transformed_pts=np.matmul(transformation_matrix,points).reshape(-1,4)[:,:A]
    return transformed_pts

def add_axis(point,value):
    N=point.shape[0]
    axisValue=np.ones((N,1))*value
    return np.concatenate([point,axisValue],axis=1)

In [102]:
rand=np.random.rand(100,2)
one=np.ones((100,1))
tr=np.random.rand(4,4)

point_transformation(rand,tr)

array([[0.63261722, 1.58022064],
       [0.49665225, 1.55169805],
       [0.43313436, 1.4274375 ],
       [0.59169277, 1.48168313],
       [0.54344848, 1.71481466],
       [0.66385219, 1.64172744],
       [0.3764921 , 1.33115066],
       [0.61992984, 1.76896755],
       [0.59525122, 1.68816395],
       [0.45114158, 0.97685165],
       [0.62926424, 1.90875227],
       [0.6317563 , 1.63065259],
       [0.43299382, 1.40403428],
       [0.51948845, 1.22484088],
       [0.45603228, 1.49824653],
       [0.43342124, 0.95756611],
       [0.3920528 , 1.35728077],
       [0.55212801, 1.17325713],
       [0.64501485, 1.84714524],
       [0.47346895, 1.46022682],
       [0.49809372, 1.37671736],
       [0.34687995, 1.10241282],
       [0.57922503, 1.38097888],
       [0.364952  , 1.33953893],
       [0.38526712, 0.91288287],
       [0.35678338, 1.16773921],
       [0.50072765, 1.34678448],
       [0.53335482, 1.54016039],
       [0.65848872, 1.44169882],
       [0.63533436, 1.79359612],
       [0.

In [71]:
deepcad_h5=h5py.File("/home/mkhan/Codes/cc3dparser/deepcad/00010110.h5","r")
cc3d_h5=h5py.File("/home/mkhan/Codes/cc3dparser/output/batch_01/171_10003/User Library-40x40 Extrusion.h5")

In [68]:
np.array(deepcad_h5['vec'])[-2]

array([  5,  -1,  -1,  -1,  -1,  -1, 192,  64, 192,  32, 128, 128, 192,
       195, 128,   0,   0])

In [77]:
np.array(cc3d_h5['vec'])

array([[  4,  -1,  -1, ...,  -1,  -1,  -1],
       [  2, 138, 128, ...,  -1,  -1,  -1],
       [  0, 162, 118, ...,  -1,  -1,  -1],
       ...,
       [  0, 204, 195, ...,  -1,  -1,  -1],
       [  5,  -1,  -1, ..., 128,   0,   0],
       [  3,  -1,  -1, ...,  -1,  -1,  -1]], dtype=int32)

In [6]:
for path,subdirs,files in os.walk("output"):
    for name in files:
        print(os.path.join(path,name))

output/batch_01/171_70860/User Library-hd-20 assembly_H-20 DE inner sleeve.h5
output/batch_01/171_70860/User Library-hd-20 assembly_H-20 DE outer sleeve.h5
output/batch_01/171_14321/User Library-offset cone.h5
output/batch_01/171_10807/User Library-pillowblock_babbit.h5
output/batch_01/171_10486/User Library-Porro Prism.h5
output/batch_01/171_12339/User Library-turbina-01-24-010_Turbina-114.h5
output/batch_01/171_10339/User Library-Video Tape Assy_vcr_labelb.h5
output/batch_01/171_10339/User Library-Video Tape Assy_vcr_labela.h5
output/batch_01/171_82968/User Library-#60 roller chain strand_#60 OUTER ROLLER CHAIN LINK - TN.h5
output/batch_01/171_82968/User Library-#60 roller chain strand_#50 INNER ROLLER CHAIN LINK.h5
output/batch_01/171_12000/User Library-base da manivela.h5
output/batch_01/171_13862/User Library-SMA Cable Connector.h5
output/batch_01/171_12168/User Library-receptacle box_Receptacle Box Side.h5
output/batch_01/171_82949/User Library-block-bigandsmall.h5
output/batch_0

In [17]:
allFiles=glob("GT_ply/*/*/*/*")
for pl in allFiles:
    f=o3d.io.read_point_cloud(pl)
    mean=np.asarray(f.points).mean(axis=0)
    std=np.asarray(f.points).std(axis=0)
    points_normalized=(np.asarray(f.points)-mean)/std
    f.points=points_normalized
    path=pl.split("/")
    o3d.io.write_point_cloud()

In [19]:
x="/data/3d_cluster/SHARP2022/Challenge2/Base-CC3D-PSE/cc3d_v1.0_ply/train/batch_02/171_94484/User Library-Steel Tread 12_125in.ply"
x.split("/").remove

ValueError: list.remove(x): x not in list

In [5]:
f=o3d.io.read_point_cloud("/data/3d_cluster/SHARP2022/Challenge2/Base-CC3D-PSE/cc3d_v1.0_ply/train/batch_02/171_94484/User Library-Steel Tread 12_125in.ply")

In [13]:
np.asarray(f.points).mean(axis=0)

array([163.9890169,  -7.456473 ,   0.       ])

In [12]:
allJsonFiles=glob(os.path.join("/data/3d_cluster/CC3D-OP-SEQ/cc3d_v3.0_recs_extrude","*/*/*"))
"/".join(allJsonFiles[0].split("/")[-3:-1])

'batch_09/171_873558'

In [4]:
def get_extrusion_index(all_stat, item_id):
    """ Get the index of the extrusion gived the id"""
    for tm in all_stat['timeline']:
        if tm['uuid'] == item_id:
            return tm['index']
    return None

In [6]:
f=json.load(open("/Users/ryzenx/Codes/Python/cc3dparser/temp_data/User Library-3DS Cart.artec_prt.json"))

In [7]:
CADSequence.from_dict(f)

Translation False
Translation False
Translation False
Translation False
Translation False
Translation False
Translation False


In [3]:
extrude_entity=f['entities'][-1]

In [4]:
extrude_entity['feature']['extrude']['refAxis']

[{'start': {'x': 0, 'y': 0.00508, 'z': -0.02424755155239188},
  'end': {'x': -0.000254, 'y': 0.00508, 'z': -0.02424755155239188},
  'direction': {'x': -1, 'y': 0, 'z': 0}}]

In [15]:
np.array(list(extrude_entity['feature']['extrude']['refAxis'][0]['start'].values()))

array([ 0.        ,  0.00508   , -0.02424755])

In [6]:
e=Extrude.from_dict(f,-1)[0]

In [48]:
bbox_2d=e.profile.bbox
zeros = np.zeros((bbox_2d.shape[0], 1))  # (N,2)
bbox_3d = np.concatenate([bbox_2d, zeros], axis=1)  # (N,3)
bbox_4d = np.concatenate(
    [bbox_3d, zeros+1], axis=1).reshape(-1, 4, 1)  # (N,4,1)

transformation_matrix_axis = e.sketch_plane.transformation_matrix_axis  # (4,4)
transformation_matrix_axis = np.broadcast_to(
    transformation_matrix_axis, (bbox_4d.shape[0], 4, 4))  # (N,4,4)

bbox_4d_transformed = transformation_matrix_axis@bbox_4d  # (N,4,1)
bbox_4d_transformed = bbox_4d_transformed.reshape(-1, 4)  # (N,4)
bbox_3d = bbox_4d_transformed[:, :3]  # (N,3)

bbox_3d=np.vstack([bbox_3d.min(axis=0),bbox_3d.max(axis=0)])

In [49]:
bbox_3d

array([[ 0.        ,  0.00502455, -0.02653939],
       [ 0.        ,  0.00508   ,  0.02424755]])

In [52]:
l=[e.bbox[0],e.bbox[0],e.bbox[0]]
np.min(l,axis=0)

array([0.        , 0.00502455, 0.02424755])

In [42]:
np.concatenate(l).reshape(-1,2,3)

array([[[ 0.        ,  0.00502455,  0.02424755],
        [ 0.        ,  0.00508   , -0.02653939]],

       [[ 0.        ,  0.00502455,  0.02424755],
        [ 0.        ,  0.00508   , -0.02653939]],

       [[ 0.        ,  0.00502455,  0.02424755],
        [ 0.        ,  0.00508   , -0.02653939]]])

In [12]:
id_="983A000001000000FFFEFF00000000007B010000"

In [13]:
def get_sketch_id(all_stat,sketch_id):
        for tm in all_stat["timeline"]:
            if tm['uuid']==sketch_id:
                return tm['index']
        return None

In [14]:
sket_entity=f['entities'][29]["sketch"]
p=Profile.from_dict(sket_entity)

In [22]:
ones=np.zeros((2,1))
np.concatenate([p.bbox,ones],axis=1)

array([[-0.02424755,  0.00502455,  0.        ],
       [ 0.02653939,  0.00508   ,  0.        ]])

In [21]:
sample_pts=p.sample_points()

In [19]:
normal_cad_plane=sket_entity["refPlane"]["normal"]

In [28]:
x_axis_3d=np.array(sket_entity["transform"]['data'][0:3])
y_axis_3d=np.array(sket_entity["transform"]['data'][3:6])
z_axis_3d=np.array(sket_entity["transform"]['data'][6:9])
origin=np.array([sket_entity["refPlane"]["origin"]["x"], sket_entity["refPlane"]["origin"]["y"], sket_entity["refPlane"]["origin"]["z"]]).reshape(-1,1)
mat=np.vstack([x_axis_3d, y_axis_3d,z_axis_3d])
ones=np.ones((1,4))

In [9]:
def transformation_matrix_axis(x_axis_3d,y_axis_3d,z_axis_3d,translation,iftranslation=False):
    rotation_mat=np.vstack([x_axis_3d, y_axis_3d,z_axis_3d])
    if iftranslation:
        translation_mat=translation.reshape(-1,1)
    else:
        translation_mat=np.zeros_like(translation.reshape(-1,1))
    transformation_mat=np.concatenate([rotation_mat,translation_mat],axis=1)
    ones=np.array([0,0,0,1]).reshape(1,4)
    translation_mat_homogeneous=np.concatenate([transformation_mat,ones])

    return translation_mat_homogeneous

In [10]:
sampled_points=p.sample_points()
sampled_points=sampled_points.reshape(-1,2)
zeros=np.zeros((len(sampled_points),1))
ones=np.ones((len(sampled_points),1))
sampled_points=np.concatenate([sampled_points,zeros,ones],axis=1)

NameError: name 'p' is not defined

In [11]:
sampled_points.shape

NameError: name 'sampled_points' is not defined

In [52]:
transformation_matrix_axis(x_axis_3d,y_axis_3d,z_axis_3d,origin,Tr)@sampled_points[0]

array([0.        , 0.00502455, 0.02424755, 1.        ])

In [63]:
sampled_points.min(axis=0)

array([-0.02424755,  0.00502455,  0.        ,  1.        ])

In [8]:
transformation_matrix_axis(x_axis_3d,y_axis_3d,z_axis_3d,origin)

NameError: name 'transformation_matrix_axis' is not defined

In [71]:
afterTrans=np.matmul(np.broadcast_to(transformation_matrix_axis(x_axis_3d,y_axis_3d,z_axis_3d,origin,True),(192,4,4)),sampled_points.reshape(-1,4,1))

In [72]:
afterTrans=afterTrans.reshape(-1,4)

In [90]:
mat=np.concatenate([mat,origin],axis=1)

In [91]:
np.concatenate([mat,ones])

array([[ 0.        ,  0.        ,  1.        ,  0.        ],
       [ 0.        ,  1.        ,  0.        ,  0.00508   ],
       [-1.        ,  0.        ,  0.        , -0.02424755],
       [ 1.        ,  1.        ,  1.        ,  1.        ]])

In [61]:
mat

array([list([0, 0, 1]), list([0, 1, 0]), list([-1, 0, 0]),
       {'x': 0, 'y': 0.00508, 'z': -0.02424755155239188}], dtype=object)

In [24]:
normal_source=np.array([0,0,1])
normal_target=np.array([-1,0,0])

In [25]:
costheta=np.dot(normal_source,normal_target)/(np.linalg.norm(normal_source)*np.linalg.norm(normal_target))


In [28]:
np.cross(normal_source,normal_target)

array([ 0, -1,  0])

In [29]:
sintheta=np.sqrt(1-costheta*2)